name: laiza
description: "A new Flutter project."
publish_to: "none" 

 
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  intl:
  image_picker: ^1.1.2
  fluttertoast: ^8.2.4

 
  cupertino_icons: ^1.0.8
  connectivity_plus: ^6.0.5
  url_launcher: ^6.3.0
  google_fonts: ^6.2.1
  flutter_bloc: ^8.1.6
  social_login_buttons: ^1.0.7
  bloc: ^8.1.4
  equatable: ^2.0.5
  loading_animation_widget: ^1.2.1
  video_player: ^2.9.1
  carousel_slider: ^5.0.0
  flutter_staggered_grid_view: ^0.7.0
  readmore: ^3.0.0
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  order_tracker_zen: ^1.0.0+4
  whitecodel_reels: ^0.0.5
  share_plus: ^10.0.2
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  firebase_storage: ^12.3.3
  cloud_firestore: ^5.4.4
  uuid: ^4.5.1
  file_picker: ^8.1.3
  get_video_thumbnail: ^0.7.0
  photo_view: ^0.15.0
  path_provider: ^2.1.4
  open_file: ^3.5.9
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.3
  googleapis_auth: ^1.6.0
  sign_in_with_apple: ^6.1.3
  zego_uikit_prebuilt_live_streaming: ^3.13.5

  flutter_localizations:
    sdk: flutter
  
  
   
   

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/json/
    - assets/l10n/


 