class ApiConstant {
  // adb shell am start -W -a android.intent.action.VIEW -d "https://laizanew.web.app/profile" com.laiza.greatminds

  // 177750485
  // f9f43319b681b8f9c13e3395781eb58fb6e8c065a957cfa12e03141b5dc3c16e
  static int appID = 397392320;
  static String appSign =
      '3403e4e2e81fbdc3325351999e71e815593f91cac4632cc1a4021c320147785c';
  static String baseUrl = 'https://laiza.encantotech.in/';
  static String baseUrlWeb = 'https://laizanew.web.app/';
  static String singUp = 'api/signup';
  static String login = 'api/login';
  static String socialLogin = 'api/social_media_login';
  static String verifyOtp = 'api/verify_otp';
  static String resendOtp = 'api/resend_otp';
  static String forgotPassword = 'api/forgot_password';
  static String verifyForgotPasswordOtp = 'api/verify_forgot_password_otp';
  static String resetPassword = 'api/reset_password';
  static String changePassword = 'api/change_password';
  static String profile = 'api/profile';
  static String updateProfile = 'api/user/update_profile';
  static String getCategories = 'api/user/all_influencer_category';
  static String getCountries = 'api/get_countries';
  static String getStates = 'api/get_states';
  static String getCities = 'api/get_cities';
  static String allInfluencers = 'api/user/get_all_influencers';
  static String allSeller = 'api/user/get_all_seller';
  static String followers = 'api/user/followers';
  static String following = 'api/user/following';
  static String unfollow = 'api/user/unfollow';
  static String follow = 'api/user/follow';
  static String myReel = 'api/user/reel';
  static String allReel = 'api/user/reel/all';
  static String allReelFromFollowedInfluencer = 'api/user/influencer/reels';
  static String userReel = 'api/user/reel/all';
  static String addReel = 'api/user/reel/add';
  static String updateReel = 'api/user/reel/update';
  static String likeReel = 'api/user/reel/add_like';
  static String removeReelLike = 'api/user/reel/remove_like';
  static String deleteReel = 'api/user/reel/delete';
  static String addComment = 'api/user/reel/add-comment';
  static String addSubComment = 'api/user/reel/add-sub-comment';
  static String updateComment = 'api/user/influencer_reel/update_comment';
  static String deleteComment = 'api/user/reel/delete_comment';
  static String deleteSubComment = 'api/user/reel/delete_comment_reply';
  static String allComment = 'api/user/reel/get_all_comment';
  static String commentReply = 'api/user/influencer_reel/get_all_comment_reply';
  static String addCommentReply = 'api/user/reel/add-sub-comment';
  static String addCommentLike = 'api/user/reel/comment/like';
  static String addSubCommentLike = 'api/user/reel/sub_comment/like';
  static String allProduct = 'api/user/product/all';
  static String allInfluencerProduct = 'api/user/influencer/product';
  static String productDetails = 'api/user/product/details';
  static String addToWishList = 'api/user/wishlist/add';
  static String removerFromWishList = 'api/user/wishlist/remove';
  static String wishlist = 'api/user/wishlist/all';
  static String cart = 'api/user/cart/all';
  static String addToCart = 'api/user/cart/add';
  static String removerFromCart = 'api/user/cart/remove';
  static String updateCart = 'api/user/cart/update';
  static String sendConnection = 'api/user/connection/send';
  static String getRequests = 'api/user/connection/requests';
  static String getMyConnections = 'api/user/get_my_connection';
  static String acceptRejectConnections = 'api/user/connection/update_requests';
  static String trendingItems = 'api/user/trending_now';
  static String fAQ = 'api/admin/faq/list';
  static String advertisement = 'api/admin/advertisement/all';
  static String getInfluencerProfile = 'api/user/get_influencer_profile';
  static String deleteUser = 'api/user/user_delete';
  static String askPromotion = 'api/user/ask/promotion';
  static String addStream = 'api/user/stream/add';
  static String getAllStream = 'api/user/stream/list';
  static String addCollection = 'api/user/collection/create-with-reels';
  static String getCollection = 'api/user/collection';
  static String getCollectionDetails = 'api/user/collection/details';
  static String deleteCollection = 'api/user/collection/delete';
  static String getPrivacy = 'api/privacy_policies';
  static String addRating = 'api/user/rate_product';
}
